struct Uniforms {
  width: u32,
  height: u32,
  step_width: u32,
  passes: u32,
  sigma_color: f32,
  sigma_normal: f32,
  sigma_depth: f32,
  sigma_albedo: f32,
  sigma_material: f32,
  glossy_protect: f32,
  exposure: f32,
  flags: u32, 
};

struct GBufferData {
  normal: vec3f,
  roughness: f32,
  albedo: vec3f,
  metallic: f32,
  motion: vec2f,
  transmission: f32,
  dist: f32,
};

@group(0) @binding(0) var<uniform> u: Uniforms;
@group(0) @binding(1) var<storage, read> in_color: array<vec4f>;
@group(0) @binding(2) var<storage, read> gbuf: array<GBufferData>;
@group(0) @binding(3) var<storage, read_write> out_color: array<vec4f>;
@group(0) @binding(4) var out_tex: texture_storage_2d<rgba8unorm, write>;

fn clamp_coord(c: vec2i, dim: vec2i) -> vec2i {
  return clamp(c, vec2i(0), dim - vec2i(1));
}

// Strips NaNs and Infs generated by stray/bad rays
fn is_valid(c: vec3f) -> bool {
  return all(c >= vec3f(0.0)) && all(c <= vec3f(10000.0));
}

fn lum(c: vec3f) -> f32 {
  return dot(c, vec3f(0.299, 0.587, 0.114));
}

// Emulates the exact tonemapping used in the renderer to map HDR to LDR
fn tonemap(c: vec3f, exposure: f32) -> vec3f {
  var color = c * exposure;
  color = color / (color + vec3f(0.3));
  return pow(color, vec3f(0.4545));
}

// ==========================================
// PASS 0: SANITIZE, MEDIAN & DEMODULATION (MAPPED TO LDR)
// ==========================================
@compute @workgroup_size(16, 16)
fn prepass_main(@builtin(global_invocation_id) id: vec3u) {
  if (id.x >= u.width || id.y >= u.height) { return; }
  let dim = vec2i(i32(u.width), i32(u.height));
  let coord = vec2i(i32(id.x), i32(id.y));
  let idx = u32(coord.y * dim.x + coord.x);

  var center_c = vec4f(0.0);
  let use_median = (u.flags & 1u) != 0u;

  if (use_median) {
    var colors: array<vec4f, 9>;
    var lums: array<f32, 9>;
    var k = 0u;
    
    for (var y = -1; y <= 1; y++) {
      for (var x = -1; x <= 1; x++) {
        let c = clamp_coord(coord + vec2i(x, y), dim);
        let col = in_color[u32(c.y * dim.x + c.x)];
        colors[k] = col;
        lums[k] = lum(col.rgb);
        k++;
      }
    }
    
    // Pure bubble sort for median (5th element) matching HTML logic
    for (var i = 0u; i < 5u; i++) {
      for (var j = i + 1u; j < 9u; j++) {
        if (lums[j] < lums[i]) {
          let tempL = lums[i]; lums[i] = lums[j]; lums[j] = tempL;
          let tempC = colors[i]; colors[i] = colors[j]; colors[j] = tempC;
        }
      }
    }
    center_c = colors[4];
  } else {
    center_c = in_color[idx];
  }

  if (!is_valid(center_c.rgb)) {
      center_c = vec4f(0.0, 0.0, 0.0, center_c.a);
  }

  // Tonemap the color to 0..1 to perfectly match the HTML image input format
  var mapped_c = tonemap(center_c.rgb, u.exposure);

  let demodulate = (u.flags & 2u) != 0u;
  let is_sky = length(gbuf[idx].normal) < 0.1;
  
  if (demodulate && !is_sky) {
    // Also tonemap the albedo guide so it scales correctly with the lighting
    let mapped_albedo = max(tonemap(gbuf[idx].albedo, u.exposure), vec3f(0.001));
    mapped_c = mapped_c / mapped_albedo;
    mapped_c = clamp(mapped_c, vec3f(0.0), vec3f(10.0)); // Safe upper bound for demodulated lighting
  }
  
  out_color[idx] = vec4f(mapped_c, center_c.a);
}

// ==========================================
// PASS 1..N: À-TROUS WAVELET TRANSFORM
// ==========================================
@compute @workgroup_size(16, 16)
fn atrous_main(@builtin(global_invocation_id) id: vec3u) {
  if (id.x >= u.width || id.y >= u.height) { return; }
  let dim = vec2i(i32(u.width), i32(u.height));
  let center_coord = vec2i(i32(id.x), i32(id.y));
  let center_idx = u32(center_coord.y * dim.x + center_coord.x);

  // This color is now in Tonemapped LDR space
  let c_color = in_color[center_idx];
  let c_gbuf = gbuf[center_idx];
  
  let kernel = array<f32, 5>(0.0625, 0.25, 0.375, 0.25, 0.0625);
  var sum_color = vec4f(0.0);
  var sum_weight = 0.0;

  let preserve = (1.0 - c_gbuf.roughness) * max(c_gbuf.metallic, c_gbuf.transmission);
  let attenuation = mix(1.0, 0.0, preserve * u.glossy_protect);

  for (var y = -2; y <= 2; y++) {
    for (var x = -2; x <= 2; x++) {
      let offset = vec2i(x, y) * i32(u.step_width);
      let sample_coord = clamp_coord(center_coord + offset, dim);
      let sample_idx = u32(sample_coord.y * dim.x + sample_coord.x);

      let s_color = in_color[sample_idx];
      let s_gbuf = gbuf[sample_idx];

      let h = kernel[x + 2] * kernel[y + 2];

      // Original Gaussian Color Falloff on LDR colors
      let c_diff = c_color.rgb - s_color.rgb;
      let w_color = exp(-dot(c_diff, c_diff) / (u.sigma_color * u.sigma_color + 1e-5));

      // Original Normal Check
      var w_normal = 1.0;
      let c_n_len = length(c_gbuf.normal);
      let s_n_len = length(s_gbuf.normal);
      if (c_n_len > 0.1 || s_n_len > 0.1) {
          let n_dot = max(0.0, dot(c_gbuf.normal, s_gbuf.normal));
          w_normal = pow(n_dot, u.sigma_normal);
      }

      // Map raw distance to 0..1 range identically to how HTML depth image was created
      let c_d_mapped = c_gbuf.dist / (c_gbuf.dist + 3.0);
      let s_d_mapped = s_gbuf.dist / (s_gbuf.dist + 3.0);
      let d_diff = c_d_mapped - s_d_mapped;
      let w_depth = exp(-(d_diff * d_diff) / (u.sigma_depth * u.sigma_depth + 1e-5));

      // Map raw Albedo to LDR
      let c_a_mapped = tonemap(c_gbuf.albedo, u.exposure);
      let s_a_mapped = tonemap(s_gbuf.albedo, u.exposure);
      let a_diff = c_a_mapped - s_a_mapped;
      let w_albedo = exp(-dot(a_diff, a_diff) / (u.sigma_albedo * u.sigma_albedo + 1e-5));

      let c_mat = vec3f(c_gbuf.transmission, c_gbuf.roughness, c_gbuf.metallic);
      let s_mat = vec3f(s_gbuf.transmission, s_gbuf.roughness, s_gbuf.metallic);
      let m_diff = c_mat - s_mat;
      let w_material = exp(-dot(m_diff, m_diff) / (u.sigma_material * u.sigma_material + 1e-5));

      var weight = h * w_color * w_normal * w_depth * w_albedo * w_material;
      
      // Apply Glass/Mirror glossy protection to neighbors
      if (x != 0 || y != 0) {
          weight *= attenuation;
      }

      sum_color += s_color * weight;
      sum_weight += weight;
    }
  }

  out_color[center_idx] = sum_color / (sum_weight + 1e-5);
}

// ==========================================
// FINAL PASS: COMPOSITE 
// ==========================================
@compute @workgroup_size(16, 16)
fn composite_main(@builtin(global_invocation_id) id: vec3u) {
  if (id.x >= u.width || id.y >= u.height) { return; }
  let idx = u32(id.y * u.width + id.x);

  var final_c = in_color[idx];
  let c_gbuf = gbuf[idx];

  let demodulate = (u.flags & 2u) != 0u;
  let is_sky = length(c_gbuf.normal) < 0.1;
  
  // Remodulate (Exclude the Sky)
  if (demodulate && !is_sky) {
    // Albedo needs to be tonemapped identically to how it was demodulated
    let mapped_albedo = max(tonemap(c_gbuf.albedo, u.exposure), vec3f(0.001));
    final_c = vec4f(final_c.rgb * mapped_albedo, final_c.a);
  }

  // We DO NOT tonemap here anymore, because it was already done in the prepass!
  textureStore(out_tex, id.xy, final_c);
}